title: Bruno Estrada
description: Data Scientist | BI Analyst | Python | SQL | Problem Solver
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/profile.jpg

plugins:
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      css: /assets/css/style.css
