title: Bruno Estrada
description: Data Scientist | BI Analyst | Machine Learning | Python | SQL | Problem Solver
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/profile-modified.png

plugins:
  - jekyll-remote-theme
